# Generated by Django 5.0.2 on 2024-06-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_delete_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='/profile_pictures/default.png', upload_to='profile_pictures'),
        ),
    ]
