# Generated by Django 5.0.2 on 2024-05-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_basket_items_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='firs_page',
            field=models.BooleanField(default=False),
        ),
    ]
