# Generated by Django 5.0.2 on 2024-06-19 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_basket_options_alter_category_options_and_more'),
        ('user', '0003_alter_customer_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
            options={
                'verbose_name': 'bought_item',
                'verbose_name_plural': 'bought_items',
                'db_table': 'bought_item',
            },
        ),
    ]
